language: node_js
node_js:
  - "4.2"
before_install: npm install -g grunt-cli
install:  npm install npm@latest
before_script: npm install grunt
script: grunt --gruntfile \ShowTracker\Gruntfile.node_js
